### ISSUE TITLE
Qt 6 Support

### ISSUE THREAD

**Issue by ghost** [herace/AnimeEffects#22]
While trying to build the project with Qt 6 I've run into all sorts of issues, as many of the Qt libraries have been either moved or deprecated, are there any plans to support it in the future?

I'm not that confident on my C++, and although I've managed to update some deprecation and build it anyway, I'm not quite certain what kind of bugs it will bring :)

Thus far I got it working with Qt 5.9, but I'll try 6 anyway, could you give me advice on how to replace OpenGL though? I tried to use the Qt5 support module and replacing the dependency, but that just created more errors :(

**Comment by Jose-Moreno** [comment]
@g-yui Hi 👋 Yes it is planned, but it is not possible right now. Qt 6 is unfortunately not fully realized and it has many issues that need to be solved before projects even consider adopting it since as you noticed it's missing a lot of libraries either by grace of deprecation or refactoring.

If you want to try you could use 5.15 which is the latest supported version for open source projects, since any other patches were locked in by the vendor of the Qt Framework until next year (they're charging for it)

As for OpenGL, to be honest I personally have no experience with it and Qt, but if you want you can visit the discord server we opened and talk with the other developers and see if they can help you further: https://discord.gg/sKp8Srm

Please keep this ticket open so the fork owner can also provide us with more feedback.

**Comment by ghost** [comment]
Will do, thanks for the swift response :)
