### ISSUE TITLE
Can't build based on instructions provided, QElapsedTimer does not have a type.

### ISSUE THREAD

**Issue by ghost** [herace/AnimeEffects#23]
Exactly as stated in the title, here's the log:

```
make[1]: Entering directory '/usr/AnimeEffects/AnimeEffects/src/gui'
g++ -c -pipe -O2 -std=gnu++11 -D_REENTRANT -Wall -W -fPIC -DAE_MAJOR_VERSION=1 -DAE_MINOR_VERSION=3 -DAE_MICRO_VERSION=4 -DAE_PROJECT_FORMAT_MAJOR_VERSION=0 -DAE_PROJECT_FORMAT_MINOR_VERSION=5 -DAE_PROJECT_FORMAT_OLDEST_MAJOR_VERSION=0 -DAE_PROJECT_FORMAT_OLDEST_MINOR_VERSION=4 -DUSE_GL_CORE_PROFILE -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I.. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/Main.o Main.cpp
In file included from ../gui/TargetWidget.h:6,
                 from ../gui/MainWindow.h:13,
                 from Main.cpp:11:
../gui/TimeLineWidget.h:81:5: error: ‘QElapsedTimer’ does not name a type; did you mean ‘QBasicTimer’?
   81 |     QElapsedTimer mElapsed;
      |     ^~~~~~~~~~~~~
      |     QBasicTimer
make[1]: *** [Makefile:2841: .obj/Main.o] Error 1
make[1]: Leaving directory '/usr/AnimeEffects/AnimeEffects/src/gui'
make: *** [Makefile:355: sub-gui-make_first-ordered] Error 2
```

Same thing happened when I tried building on Windows, on Linux (via WSL) I built with the exact instructions provided, on Windows I did it with Qt5 and MSVC

**Comment by Jose-Moreno** [comment]
@g-yui Hi! I had this problem myself before using a more recent version of Qt framework. The issue seemed to be that QElapsedTimer is not included in the file `TimeLineWidget.h` so you have to `#include <QElapsedTimer>` mainly because the other instruction (`<QTimer>` I think) was deprecated and the new instruction `<QElapsedTimer>` doesn't have have backwards compatibility by default unless you're using a newer version (I'm currently using 5.15.2)

I literally just added the include and it started working, so try that out first. If it works for you please leave this open and we'll see about linking a PR to this so we can close it once this instruction has been added, though I think the easiest solution is to upgrade the Qt framework SDK 👍

Additionally a new anime effects repository and organization was created where we have a bit more control. Herace is still a contributor but this fork might no be the primary one we will follow in the near future. Just something to take into account. You can visit the repos here: https://github.com/AnimeEffectsDevs/AnimeEffects

**Comment by ghost** [comment]
Oh gotcha! Will check it out ;)
