### ISSUE TITLE
[Feature Request] Show frame number / Timeline scales

### ISSUE THREAD

**Issue by larpon** [herace/AnimeEffects#7]
Hi,
I'm experimenting with having a current frame showed somewhere in the UI in addition to the time scale indication which is based on `fps` interpolation (1.0 = f60, 2.0 = f120).

I've [done an attempt](https://github.com/Larpon/AnimeEffects/tree/experiment/show-current-frame-in-time-cursor) to set it in the cursor in the timeline, but it's not a very good solution so far.
![image](https://user-images.githubusercontent.com/768942/68770785-17bd6200-0627-11ea-9e05-7e1a4d61cfcd.png)

Does anyone have any ideas of were we could put it in the UI?

I've also thought about a dedicated [info widget](https://github.com/Larpon/AnimeEffects/tree/feature/info-widget) or an info bar somewhere.

It'd be nice with some input on this.

**Comment by herace** [comment]
Hrrmmmm, ill have to investigate and clone your branch to take a look at this when i return home. 🤔

**Comment by larpon** [comment]
Well - it's just an idea of where to put it - I know it's ugly as-is but maybe we can find somewhere else to put a label for current frame. It's quite essential info to have if you need it for some thing that uses frame-by-frame animation. Like spritesheets in a game etc. Knowing which frame you're on would be a big help :)

**Comment by Jose-Moreno** [comment]
In general since the "frame strip" in animation software only indicates a certain amount of frame increments there are two distinct choices for this:

1. The frame indicator is seen on the frame strip (as in your current proposal) A few programs implement it like this such as Pencil2D, OpenToonz (timeline mode), the excellent Clip Studio Paint. and Blender (2.8.x series)
2. The frame indicator is separate from the time indicator (usually in the timeline but sometimes in another panel or status bar). You see this in Flash / Animate CC, After Effects, TVPaint, Toonboom Harmony, Krita 

If you notice option two is very widespread and you could even say it's "industry standard" however that doesn't mean it's "better" just because there's more of it. 

I personally favor the way you've already implemented it because when you're animating you don't want to be looking at three different places for the frame number. If you place the timeline indicator you should know immediately what frame you're at. I could argue that the frame number could be better on the viewport canvas screen though...

Either way if you want to make it "prettier" take a look at how Blender implements it:

Zoomed-out timeline
![image](https://user-images.githubusercontent.com/4912907/68835660-91386d00-0686-11ea-93e9-340dcf2d8a8f.png)

Zoommed-in timeline
![image](https://user-images.githubusercontent.com/4912907/68835677-98f81180-0686-11ea-89d0-ac6abdddc076.png)

I present blender because a. the keyframes look similar to AnimeEffects (diamond shape) and b. it's open source so you could theoretically take a look at the underlying code (although it's C :sweat_drops: )

Although it's not that different from yours, the things we can learn from them is that the frame number needs more contrast against the container itself, and the timeline indicator also needs to be of a bright color, otherwise you'll get lost when perusing the timeline. Normally a bright red or green is used for the timeline indicator, and the number could be highlighted in white or yellow.

**Comment by larpon** [comment]
Really useful points here @Jose-Moreno - if we are to have it in the scrubber as I suggested, it probably need to follow the scale on the timeline. That means we might have to make an option to also support a frame based timeline scale. What do you think? Personally I'm used to working with frame based animation exclusively.

It should be fairly easy to make the scrubber prettier than my illustrative quick hack :)

**Comment by Jose-Moreno** [comment]
Well I also showed Blender as an example precisely because of how they treat the timeline zoom as scaling the timeline does not scale the widget as seen in the previously posted pictures.

Regarding having a frame based visualization:

1. It would also be ideal to have a visualization cyclic toggle like other software, where you can toggle between several options like:
- SMPTE timecode (HH:MM:SS:FF) I don't think we need the HH:MM:SS:MSEC one
![image](https://user-images.githubusercontent.com/4912907/68889119-49e3c800-06ea-11ea-8038-d5865a7775fc.png)
- Seconds + Frames / Seconds : Frames
![image](https://user-images.githubusercontent.com/4912907/68889039-1e60dd80-06ea-11ea-9347-7cae07300db6.png)
- Total frames with digit padding for hours [4] or minutes [3] e.g 0000 vs. 000

Here's for example the formats CSP manage:

![image](https://user-images.githubusercontent.com/4912907/68887511-1f444000-06e7-11ea-89a3-02fba55b3792.png)

I don't know how it works on code but I assume we're working with miliseconds here, if that's the case then it's a matter of presentation as converting miliseconds to frames should be pretty straightforward by multiplying over the FPS factor.

2. Another thing we need to review is the FPS. Right now it's set to 60 fps, since I take this app was originally meant for games animation, however if this is going to become an all purpose cut out / modular animation tool, we need to be allowed to change the FPS setting at least to:
- 24 (film)
- 25 (PAL)
- 30 (NTSC)
- 60 (Games)

Even though the max length of any scene is given in frames (max frames option) it would be beneficial to display frame markings depending on the FPS, that is if you set to 24, make it so you see increments on halves (0,12,24, etc) if it's 30fps (0,15,30, etc) 25 it's (1,13,25),  60 (0,30,60) This shouldn't suppose a problem as there are already markings, which you can notice this because the frame strip counts 0.0 > 0.5 [30f] > 1.0 [60f] and so on.

Not sure if these points should be specifically discussed here or if they should be in separate issues though.

**Comment by larpon** [comment]
I agree that it should support different timelines (timeline scales) indeed (what I referred to as scales as it's "just" linear conversion between numbers on the timeline). Having different ways of showing this calls for a dedicated "bar" or strip somewhere (as e.g. HH:MM:SS:msms won't fit in the scrubber) :smile: 

Next problem here is then *where* to put it. I suppose we could grab some space from the bottom of the "Target dock"?

Like on this ugly mock-up:
![image](https://user-images.githubusercontent.com/768942/68933372-ce8b2080-0794-11ea-9755-771e9fd80ec7.png)

**Comment by Jose-Moreno** [comment]
For showing "timeline stuff" I think a customized status bar will work fine. There's also a trend to include the timeline zoom below. For reference here are some captures of different animation programs with similar qualities:

Flash MX
![image](https://user-images.githubusercontent.com/4912907/68963658-7577b880-07a5-11ea-8ae4-0a848b479a2a.png)

Flash CS6
![image](https://user-images.githubusercontent.com/4912907/68963729-a526c080-07a5-11ea-96af-846b48a25711.png)

TVPaint
![image](https://user-images.githubusercontent.com/4912907/68963887-02227680-07a6-11ea-8dc0-03869d9222ec.png)

_Note: To the right to the [1/1] <> [Current Frame / Total Frames] -- The selected tool name will also be displayed._

TB Harmony:
![image](https://user-images.githubusercontent.com/4912907/68965084-fab09c80-07a8-11ea-91c6-6438f3335ab6.png)

After Effects
![image](https://user-images.githubusercontent.com/4912907/68965202-3e0b0b00-07a9-11ea-81cc-8516c9dbec72.png)

I Personally don't mind where the timeline info is as long as it's consistent and contains all the critical information an animator needs 90% of the time, such as:
- FPS
- Timescale Widget
    - Current Frame (This can be either part of the timescale widget or separate)
    - Scene Frame Length
- Zoom Slider

I initially like the bottom status bar idea but If it's going to be put towards the bottom part of the panel I think the status bar should be below the sliders, but that's just a matter of preference as I like the timeline sliders to visually map 1:1 to the timeline motion, it's not a technical impediment as far as I'm concerned.
